# Joget DX8 Configuration
# Main configuration file for Joget utility

# Base configuration
base_url: http://localhost:8080/jw/api/form
default_api_key: 3e56045fe2394b5ba8fb148e74edc029
# base_url: http://localhost:9999/jw/api/form
# default_api_key: 8c04d5332aa34484a62fe1fb1e6e5900

# Data paths configuration
data_paths:
  default: ./data
  metadata: ./data/metadata
  csv: ./data/csv
  json: ./data/json

# Connection settings
connection:
  timeout: 30  # seconds
  retry_count: 3
  retry_delay: 2  # seconds

# Standard metadata endpoints
# These endpoints all use the standard code/name field structure
metadata_endpoints:
  employmentType:
    api_id: API-bb8dc2d3-892f-5245-b38f-94375249f855
    description: "Employment types"

  department:
    api_id: API-cc9ed3e4-9a3g-6356-c49g-a5486360g966
    description: "Department list"

# Custom endpoints with specific field mappings
endpoints:
  customer:
    api_id: API-dd1fe4f5-ab4h-7467-d51h-b6597471h077
    required_fields:
      - customerId
      - customerName
    field_mapping:
      id: customerId
      name: customerName
      email: customerEmail
      phone: customerPhone

  account:
    api_id: API-ee2gf5g6-bc5i-8578-e62i-c7618582i188
    required_fields:
      - accountNumber
      - accountType
    field_mapping:
      number: accountNumber
      type: accountType
      balance: accountBalance
      currency: accountCurrency

  farmers_registry:
    api_id: API-6dbc76a7-e38f-47c6-af25-ad0783c13859
    # This endpoint uses a different URL structure
    full_path: govstack/processing/services/farmers_registry/applications
    required_fields: []
    field_mapping: {}

  farmerForm:
    api_id: API-bd029636-b858-4d66-8726-a9bf6feeea12
    description: "Farmer registration form"
    full_path: govstack/processing/services/farmers_registry/applications
    required_fields: []
    field_mapping: {}

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: ./logs/joget_utility.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Metadata management configuration
# Pattern 2 Subcategory Mappings (for nested LOV relationships)
# These define parent-child relationships where child CSV does NOT contain FK column
# The FK must be injected during form generation and data population
subcategory_mappings:
  # Equipment Categories → Equipment Types
  md25equipmentCategory:
    TILLAGE: md25tillageEquipment
    PLANTING: md25plantingEquipment
    PEST_CONTROL: md25pestControlEquipment
    IRRIGATION: md25irrigationEquipment
    STORAGE: md25storageEquipment
    PROCESSING: md25processingEquipment
    TRANSPORT: md25transportEquipment
    GENERAL_TOOLS: md25generalTools
    LIVESTOCK_EQUIP: md25livestockEquipment

  # Input Categories → Input Types
  md27inputCategory:
    SEEDS: md19crops
    FERTILIZER: md27fertilizer
    PESTICIDES: md27pesticide
    LIVESTOCK_VET: md27livestockSupply
    IRRIGATION: md27irrigation

# Metadata processing options
metadata:
  # Automatically detect relationships between metadata forms
  auto_detect_relationships: true

  # Parse metadata-overview.docx for documented relationships
  parse_metadata_overview: true
  metadata_overview_path: ./docs/metadata-overview.docx

  # Validate nested LOV structures
  validate_nested_lovs: true

  # Enable FK field injection for Pattern 2 forms
  inject_fk_fields: true

  # Paths
  csv_path: ./data/metadata
  forms_path: ./data/metadata_forms
  relationships_file: ./data/relationships.json

  # Form generation behavior
  overwrite_existing_forms: false
  backup_before_overwrite: true
  backup_dir: ./data/metadata_forms/.backups